### ISSUE TITLE
Orderbook details doesn't show bid offers closest to the spread

### ISSUE THREAD

**Issue by irisli** [stellar/go-horizon#322] opened 2017-01-10 21:05 UTC
Maybe I have something inverted? Right now internally, i use base/buying and counter/selling. But I pass it into Horizon Details for Orderbook backwards. Now i'm questioning everything about whether I got the trades correct (there are 16 different ways that the orderbook could be setup and interpreted).

Laboratory link:
> https://www.stellar.org/laboratory/#explorer?resource=order_book&endpoint=details&values=eyJzZWxsaW5nX2Fzc2V0Ijp7InR5cGUiOiJuYXRpdmUiLCJjb2RlIjoiVVNEIiwiaXNzdWVyIjoiR0JBVVVBNzRINFhPUVlSU09XMlJaVUE0UUw1UEIzN1UzSlM1TkUzUlRCMkVMSlZNSUY1UkxNQUcifSwiYnV5aW5nX2Fzc2V0Ijp7InR5cGUiOiJjcmVkaXRfYWxwaGFudW00IiwiY29kZSI6IlVTRCIsImlzc3VlciI6IkdCQVVVQTc0SDRYT1FZUlNPVzJSWlVBNFFMNVBCMzdVM0pTNU5FM1JUQjJFTEpWTUlGNVJMTUFHIn19&network=test

My interpretation of this data:
> ![image](https://cloud.githubusercontent.com/assets/5728307/21824696/6afc68b8-d735-11e6-96b2-85f21b944160.png)
> https://stellarterm.com/

**Comment by nullstyle** [comment] 2017-01-10 21:42
Duplicate of #318, I believe.  These assertions (https://github.com/stellar/horizon/blob/master/src/github.com/stellar/horizon/db2/core/order_book_summary_test.go#L33-L56) confirm the behavior at the database level, so if the issue is still occurring, perhaps it is occurring at a higher level.

**Closed as completed** 2017-01-12 21:46 UTC
