### ISSUE TITLE
links returned by trades for orderbook return wrong assets

### ISSUE THREAD

**Issue by poliha** [stellar/go-horizon#396] opened 2017-09-08 13:50 UTC
Consider the response for this query to get trades

https://horizon-testnet.stellar.org/order_book/trades?selling_asset_type=native&buying_asset_type=credit_alphanum4&buying_asset_code=C&buying_asset_issuer=GAFGHZQYR7PZVAQJZKJW5FPDIHFTTC66RE5ZNPNY2OVTZJLCCW3H2JHM&order=desc

then also consider the next page link
https://horizon-testnet.stellar.org/order_book/trades?order=desc&limit=10&cursor=16203786326380545-1

the results on the next page shows trades for asset pairs  that are not part of the original query. Shouldn't the next page return trades related to the current asset pairs? or may be an empty array if no further trades.

I think the returned links should include buying and selling asset in the query params.

**Comment by nullstyle** [comment] 2017-09-08 17:31
@poliha yeah, it looks like we're not rendering the next link correctly.

**Comment by irisli** [comment] 2017-09-14 22:34
No wonder StellarTerm charts are so weird lol. I just repro'ed this issue. :+1: It's not a huge issue but lots of bycatches and discards (https://en.wikipedia.org/wiki/Discards)

**Comment by irisli** [comment] 2017-09-14 22:50
One anecdote: I walked through 720 trades and only 104 were relevant to me. It's not too bad but i think thats because the pair i was walking through had 104/720 of the past trades?

Also, oddly, for some reason, when I try to get 200 trades at a time, it's different from getting 100 trades at a time.

**Comment by nullstyle** [comment] 2017-09-14 23:06
Yeah, it's totally busted at present.

**Comment by irisli** [comment] 2017-09-14 23:11
### EDIT: there was a bug in my code so the results aren't all that bad, but there are still sometimes irrelevant items

In case you want something to use to repro:

Here is my walker script: 
https://github.com/irisli/stellarterm/blob/master/api/functions/utils/tradeWalker.js

And the harness to that script:
https://github.com/irisli/stellarterm/blob/master/api/functions/utils/testWalker.js

The only dependency needed to run that is to do a `npm install` in the stellarterm/api folder

**Comment by nullstyle** [comment] 2017-09-18 19:34
This is going to take more work than a simple fix.  The problem is in the very simpistic implementation of `PopulateLinks()` method of `*Page`.  I need to switch from using `BasePath` to considering the full request url when building the next set of links.

**Comment by tomerweller** [comment] 2017-11-08 00:27
Closing and moving to the monorepo: 
https://github.com/stellar/go/issues/148

**Closed as completed by tomerweller** 2017-11-08 00:27 UTC
Labels: in progress
