### ISSUE TITLE
Streaming with cursor=now does not send an initial response

### ISSUE THREAD

**Issue by alinnow** [stellar/go-horizon#437] opened 2018-03-07 12:09 UTC
With cursor=now, the server does not send any initial response (i.e. HTTP headers and open/hello event). With a cursor that returns at least one event, the initial response is sent as requested. Such requests are shown as failed (cancelled) in Chrome after 15 seconds.

This is affecting us at SatoshiPay.

Expected:
The server should send the **HTTP response headers** and open/hello event _immediately_ with cursor=now.

`curl` traces (current behaviour) below.

Response with cursor=now:

```
$ curl --trace-time --verbose 'https://horizon-testnet.stellar.org/accounts/GBSFOUHV2TMCDU45JK2A7YZD2JEBJJQ6UWV3FWGA6U5DGC6GMPQNITRW/effects?cursor=now' -H 'Accept:text/event-stream'                                                                                                                                      
12:32:17.187358 *   Trying 23.23.139.123...
12:32:17.187401 * TCP_NODELAY set
12:32:17.294582 * Connected to horizon-testnet.stellar.org (23.23.139.123) port 443 (#0)
12:32:17.294730 * ALPN, offering h2
12:32:17.294752 * ALPN, offering http/1.1
12:32:17.294811 * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
12:32:17.299441 * TLSv1.2 (OUT), TLS header, Certificate Status (22):
12:32:17.299473 * TLSv1.2 (OUT), TLS handshake, Client hello (1):
12:32:17.408472 * TLSv1.2 (IN), TLS handshake, Server hello (2):
12:32:17.416194 * TLSv1.2 (IN), TLS handshake, Certificate (11):
12:32:17.416699 * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
12:32:17.416803 * TLSv1.2 (IN), TLS handshake, Server finished (14):
12:32:17.416954 * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
12:32:17.416975 * TLSv1.2 (OUT), TLS change cipher, Client hello (1):
12:32:17.417046 * TLSv1.2 (OUT), TLS handshake, Finished (20):
12:32:17.523793 * TLSv1.2 (IN), TLS change cipher, Client hello (1):
12:32:17.523845 * TLSv1.2 (IN), TLS handshake, Finished (20):
12:32:17.523881 * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
12:32:17.523905 * ALPN, server did not agree to a protocol
12:32:17.523929 * Server certificate:
12:32:17.523961 *  subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.stellar.org
12:32:17.523989 *  start date: Jul 17 00:00:00 2017 GMT
12:32:17.524023 *  expire date: Aug 16 23:59:59 2018 GMT
12:32:17.524059 *  subjectAltName: host "horizon-testnet.stellar.org" matched cert's "*.stellar.org"
12:32:17.524099 *  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
12:32:17.524122 *  SSL certificate verify ok.
12:32:17.524179 > GET /accounts/GBSFOUHV2TMCDU45JK2A7YZD2JEBJJQ6UWV3FWGA6U5DGC6GMPQNITRW/effects?cursor=now HTTP/1.1
12:32:17.524179 > Host: horizon-testnet.stellar.org
12:32:17.524179 > User-Agent: curl/7.58.0
12:32:17.524179 > Accept:text/event-stream
12:32:17.524179 > 
12:33:17.000805 < HTTP/1.1 504 GATEWAY_TIMEOUT
12:33:17.000893 < Content-Length: 0
12:33:17.000987 < Connection: keep-alive
12:33:17.001094 < 
12:33:17.001169 * Connection #0 to host horizon-testnet.stellar.org left intact

```

Response with cursor set to before the last transaction:

```
$ curl --trace-time --verbose 'https://horizon-testnet.stellar.org/accounts/GBSFOUHV2TMCDU45JK2A7YZD2JEBJJQ6UWV3FWGA6U5DGC6GMPQNITRW/effects?cursor=33292958685995009-1' -H 'Accept:text/event-stream' 
12:30:54.931029 *   Trying 50.16.237.67...
12:30:54.931088 * TCP_NODELAY set
12:30:55.043685 * Connected to horizon-testnet.stellar.org (50.16.237.67) port 443 (#0)
12:30:55.043831 * ALPN, offering h2
12:30:55.043854 * ALPN, offering http/1.1
12:30:55.043912 * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
12:30:55.048560 * TLSv1.2 (OUT), TLS header, Certificate Status (22):
12:30:55.048589 * TLSv1.2 (OUT), TLS handshake, Client hello (1):
12:30:55.162189 * TLSv1.2 (IN), TLS handshake, Server hello (2):
12:30:55.163025 * TLSv1.2 (IN), TLS handshake, Certificate (11):
12:30:55.163503 * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
12:30:55.163599 * TLSv1.2 (IN), TLS handshake, Server finished (14):
12:30:55.163746 * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
12:30:55.163777 * TLSv1.2 (OUT), TLS change cipher, Client hello (1):
12:30:55.163825 * TLSv1.2 (OUT), TLS handshake, Finished (20):
12:30:55.275840 * TLSv1.2 (IN), TLS change cipher, Client hello (1):
12:30:55.275902 * TLSv1.2 (IN), TLS handshake, Finished (20):
12:30:55.275937 * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
12:30:55.275959 * ALPN, server did not agree to a protocol
12:30:55.275991 * Server certificate:
12:30:55.276028 *  subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.stellar.org
12:30:55.276055 *  start date: Jul 17 00:00:00 2017 GMT
12:30:55.276087 *  expire date: Aug 16 23:59:59 2018 GMT
12:30:55.276119 *  subjectAltName: host "horizon-testnet.stellar.org" matched cert's "*.stellar.org"
12:30:55.276152 *  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
12:30:55.276176 *  SSL certificate verify ok.
12:30:55.276228 > GET /accounts/GBSFOUHV2TMCDU45JK2A7YZD2JEBJJQ6UWV3FWGA6U5DGC6GMPQNITRW/effects?cursor=33292958685995009-1 HTTP/1.1
12:30:55.276228 > Host: horizon-testnet.stellar.org
12:30:55.276228 > User-Agent: curl/7.58.0
12:30:55.276228 > Accept:text/event-stream
12:30:55.276228 > 
12:30:55.577977 < HTTP/1.1 200 OK
12:30:55.577997 < Access-Control-Allow-Origin: *
12:30:55.578020 < Cache-Control: no-cache
12:30:55.578044 < Content-Type: text/event-stream; charset=utf-8
12:30:55.578067 < Date: Wed, 07 Mar 2018 11:30:54 GMT
12:30:55.578091 < Vary: Origin
12:30:55.578115 < X-Ratelimit-Limit: 18000
12:30:55.578144 < X-Ratelimit-Remaining: 17992
12:30:55.578168 < X-Ratelimit-Reset: 2735
12:30:55.578191 < transfer-encoding: chunked
12:30:55.578214 < Connection: keep-alive
12:30:55.578238 < 
retry: 1000
event: open
data: "hello"

id: 33292958685995009-2
data: {"_links":{"operation":{"href":"https://horizon-testnet.stellar.org/operations/33292958685995009"},"succeeds":{"href":"https://horizon-testnet.stellar.org/effects?order=desc\u0026cursor=33292958685995009-2"},"precedes":{"href":"https://horizon-testnet.stellar.org/effects?order=asc\u0026cursor=33292958685995009-2"}},"id":"0033292958685995009-0000000002","paging_token":"33292958685995009-2","account":"GBSFOUHV2TMCDU45JK2A7YZD2JEBJJQ6UWV3FWGA6U5DGC6GMPQNITRW","type":"account_credited","type_i":2,"asset_type":"native","amount":"9999.9999900"}

12:31:55.306675 * TLSv1.2 (IN), TLS alert, Client hello (1):
12:31:55.306708 * transfer closed with outstanding read data remaining
12:31:55.306723 * stopped the pause stream!
12:31:55.306748 * Closing connection 0
12:31:55.306790 * TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (18) transfer closed with outstanding read data remaining
```

**Comment by bolshoy** [comment] 2018-03-26 11:27
happens here too, have to use the cursor which is one before the last

**Comment by andywer** [comment] 2018-03-27 09:55
~~Not sure if an initial hello event would make sense.~~

It seems to boil down to two primary issues:
- No HTTP headers sent in the response
- No keep-alive comments being sent

Regarding the timeout: The [Mozilla Server-send events docs](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) (Section "Event stream format") say that:

> The event stream is a simple stream of text data which must be encoded using UTF-8. Messages in the event stream are separated by a pair of newline characters. A colon as the first character of a line is in essence a comment, and is ignored.

> Note: The comment line can be used to prevent connections from timing out; a server can send a comment periodically to keep the connection alive.

The horizon should probably send a keep-alive comment initially and then once in a while.

**Comment by alinnow** [comment] 2018-03-27 13:06
@andywer The keep-alive comments are not super-important: a decent load-balance/reverse proxy will keep such connections open, even without data.

There is anyhow already an issue to workaround that, namely https://github.com/stellar/go/issues/376

**Comment by bolshoy** [comment] 2018-03-27 15:02
@alanpearce the stock ELB recycles inactive connections after 60 seconds. And considering that the SSE connection can be silent for a long time, you will need keepalives, or you will have to reconnect each minute.

**Comment by nullstyle** [comment] 2018-03-27 16:24
Historical note:  This is by design in the current horizon, at the request of a earlier integrator.  It's quite easy/normal for devs to forget to supply an error handler in their code and end up in a situation where errors are being silently discarded on the client site.   Instead, we avoid sending any data on the wire before we have any real results to show you such that we can abort with a regular http error response with a non-success status code to make the error state more clear to integrators.

Anyways, we'll be adding heartbeat support soon to SSE connections and along with it this behavior will be changed to the desired state.

**Comment by alinnow** [comment] 2018-03-28 07:34
@bolshoy We run our own Horizon server at SatoshiPay which is not using ELB; for us the connections will not be closed if an event-stream is quiet for some time.

**Comment by nullstyle** [comment] 2018-03-29 00:21
Fixed in https://github.com/stellar/go/pull/379

**Closed as completed by nullstyle** 2018-03-29 00:21 UTC
