### ISSUE TITLE
order_book/trades returning trades for the wrong order book

### ISSUE THREAD

**Issue by johansten** [stellar/go-horizon#308] opened 2016-09-24 11:56 UTC
```
buying_asset_type    native
selling_asset_code  FUNT
selling_asset_issuer GBUYUAI75XXWDZEKLY66CFYKQPET5JR4EENXZBUZ3YXZ7DS56Z4OKOFU
selling_asset_type  credit_alphanum4
```

On testnet, this gives me back trades for ZAR / USD.

**Comment by nullstyle** [comment] 2017-01-10 18:05
This is a duplicate of #318 which I will get fixed today.  Closing this now because #318 has more info about the issue.

**Closed as completed by nullstyle** 2017-01-10 18:05 UTC
