### ISSUE TITLE
Can not acceptting trust on assets 

### ISSUE THREAD

**Issue by gastzars** [stellar/go-horizon#440] opened 2018-03-15 09:37 UTC
i'm getting 'tx_bad_seq'  error when trying to `changeTrust` on my issued assets.

**Comment by bartekn** [comment] 2018-03-15 11:10
Sequence number on you transaction is invalid. This is not a bug so I'm closing this issue.

More information:
- https://www.stellar.org/developers/guides/concepts/transactions.html#possible-errors
- https://www.stellar.org/developers/guides/concepts/list-of-operations.html#change-trust
- https://stellar.stackexchange.com/

**Closed as completed by bartekn** 2018-03-15 11:10 UTC
