### ISSUE TITLE
path result record seems to be wrong

### ISSUE THREAD

**Issue by TbLtzk** [stellar/go-horizon#240] opened 2016-01-27 22:53 UTC
```
{
        "source_asset_type": "native",
        "source_amount": "25.2424242",
        "destination_asset_type": "native",
        "destination_amount": "50.0000000",
        "path": [
          {
            "asset_type": "credit_alphanum4",
            "asset_code": "AAA",
            "asset_issuer": "GAX4CUJEOUA27MDHTLSQCFRGQPEXCC6GMO2P2TZCG7IEBZIEGPOD6HKF"
          }
        ]
      }
```

I think there might be a bug in the paths calculation: the below request returns 2 possible payments. One is the simple direct XLM payment, the other is pasted above. Seems as if `source_asset_type` should be `credit_alphanum4` and `source_asset_type` should be `AAA`
https://horizon-testnet.stellar.org/paths?destination_account=GDJXQYEWDPGYK4LGCLFEV6HBIW3M22IK6NN2WQONHP3ELH6HINIKBVY7&source_account=GAN65D2FEI63T4MBMOWWOP3K7VS6SVI5T6NNKIHNCI6PN32IGF6OVKSS&destination_amount=50&destination_asset_type=native

**Comment by nullstyle** [comment] 2016-01-28 11:18
This is not a bug as far as I can tell, @TbLtzk.  

The source account for that request `GAN...` does not hold `AAA` credits, and so `AAA` cannot be the source asset.  In fact, that account only holds a native balance.  Why do you think the source should be `AAA`?  I ask because this is probably a failure of our documentation so I was hoping to understand where it is failing, so we can improve it.

**Comment by TbLtzk** [comment] 2016-01-28 12:15
Ok, you're right it can't be the source asset. But why is it returned as possible payment and why does it fail when I use this path option?
Furthermore it seems weired that I would have negative path costs (send 25.24242 and receiver gets 50)

**Comment by nullstyle** [comment] 2016-01-28 12:19
What is the error returned when it fails?

As far as the cost, first I want to point out #239.  So, the costs are currently broken (and most likely the source of your failed transaction).  But in regards to your question about negative costs, that's a viable situation...  there's nothing stopping the exchange rate from being over 1.0.

I'm going to go ahead and close this, but feel free to add your specific failure as a comment, or open a new issue with that information.

Sorry about the pain!

**Closed as completed by nullstyle** 2016-01-28 12:19 UTC

**Comment by TbLtzk** [comment] 2016-01-28 13:22
The error code is
`op_over_source_max`
maybe I need to add a small buffer. The transaction XDR is `AAAAABvuj0UiPbnxgWOtZz9q/WXpVR2fmtUg7RI89u9IMXzqAAAAZAAIbNwAAAAqAAAAAAAAAAAAAAABAAAAAAAAAAIAAAAAAAAAAA8LsDIAAAAA03hglhvNhXFmEspK+OFFts1pCvNbq0HNO/ZFn8dDUKAAAAAAAAAAAB3NZQAAAAABAAAAAUFBQQAAAAAAL8FRJHUBr7BnmuUBFiaDyXELxmO0/U8iN9BA5QQz3D8AAAAAAAAAAUgxfOoAAABAIALUg3DyNoZtmFbEzUHPA50wGcaCf9nLreqfPanjOog+xBpcCrfCQ7aBWGr6fA+t0XR49zM9RhMl7N2dEuarAg==`

**Comment by TbLtzk** [comment] 2016-01-28 13:23
AH ok this MIGHT be effect of #239
However I don't understand how the actual path would look like. I would expect at least two hops. XLM-> 'AAA' and 'AAA' to XLM

**Comment by nullstyle** [comment] 2016-01-28 13:35
Yeah, this seems like #239 in effect... I got bit by it yesterday while I was preparing for a talk I gave here in Lagos.

As far as the understanding the path:  The `source_asset` defines the start of the path, the `destination_asset` defines the end of the path, and the `path` attribute defines any intermediary stops in the path.  This form was chosen because it aligns with the schema for `PathPaymentOp`, the underlying XDR struct that drives the whole thing...  that alignment should make integration much easier.  The path defines the points on the line, not the spans.

**Comment by TbLtzk** [comment] 2016-01-28 19:09
Thanks for your help, think I got it, now!
Final question then, just to be sure: if I have one conversion, let's say EUR -> XRP, the paths array would be empty and I would only know by comparing source and destination asset, that a conversion is involved, right?

**Comment by jedmccaleb** [comment] 2016-01-28 19:30
that's right
