### ISSUE TITLE
When making a Stellar REST API call  with a limit of more than 200 items, it causes a server 500 error.

### ISSUE THREAD

**Issue by philbartholo** [stellar/go-horizon#371] opened 2017-07-07 23:25 UTC
To reproduce:

https://horizon.stellar.org/accounts/GAZTZ2T322AFOONMXBN5P3MILKX7QS5BPKHZZVPUXZLCQ6JPBWMDGH5P/operations?limit=201

Recommend adding max of 200 limit to documentation and gracefully returning an error message when exceeded rather than  a server 500 crash.

**Comment by bartekn** [comment] 2017-07-07 23:47
Thanks, but it's a duplicate of https://github.com/stellar/horizon/issues/365

**Closed as completed by bartekn** 2017-07-07 23:47 UTC
